- name: prac on loops
  hosts: local  
  connection: local
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
     name: "{{ item.name }}"
     state: "{{ item.state }}"
    loop:
    - { name: "mysql", state: "present"}
    - { name: "python", state: "absent"}
    - { name: "nginx", state: "present"} 