- name: install and run Apache
  hosts: web
  become: yes
  tasks:
    - name: install Apache
      ansible.builtin.package:
        name: httpd
        state: present

    - name: start and enable Apache
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
